# -*- coding: utf-8 -*-
"""Chemist Warehouse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4gS2GpTtTgTQmFr4QdjT9Lbb_DGzfU6
"""

import sys
# Install the client in a separate step if needed
!{sys.executable} -m pip install -q apify-client

from apify_client import ApifyClient
from google.colab import userdata
import time


raw_token = userdata.get('META_AD_API_KEY')
token = raw_token.strip() if raw_token else None

if not token:
    print("Error: KEY not found in Colab secrets or is empty.")
else:
    client = ApifyClient(token)
    actor_id = "XtaWFhbtfxyzqrFmd"

    try:
        print(f"Fetching the latest run for actor ID: {actor_id}...")
        runs_list = client.actor(actor_id).runs().list(limit=1, desc=True)
        runs = runs_list.items

        if runs:
            last_run = runs[0]
            print(f"Found last run with ID: {last_run['id']}")
            print("Fetching results (printing first 5 items)... ")

            count = 0
            for item in client.dataset(last_run['defaultDatasetId']).iterate_items():
                from IPython.display import display
                display(item)
                count += 1
                if count >= 5: break
        else:
            print(f"No runs found for actor ID '{actor_id}'.")

    except Exception as e:
        print(f"An error occurred: {e}")

first_item = next(
    client.dataset(last_run.default_dataset_id).iterate_items()
)

print(first_item.keys())

import pandas as pd

items = list(client.dataset(last_run.default_dataset_id).iterate_items())

df = pd.json_normalize(items)

df.head()

df.shape

keep_cols = [

    # Identity
    'ad_archive_id',
    'collation_id',
    'is_active',

    # Dates
    'start_date_formatted',
    'end_date_formatted',
    'total_active_time',

    # Advertiser
    'page_name',
    'snapshot.page_name',

    # Creative
    'snapshot.title',
    'snapshot.body.text',
    'snapshot.caption',
    'snapshot.link_description',
    'snapshot.cta_text',
    'snapshot.cta_type',
    'snapshot.display_format',

    # URL
    'snapshot.link_url',

    # Media
    'snapshot.cards',
    'snapshot.images',
    'snapshot.videos',

    # Platform
    'publisher_platform',

    # Reach
    'impressions_with_index.impressions_text',
    'impressions_with_index.impressions_index',

    # Page metrics
    'snapshot.page_like_count'
]

curated_df = df[keep_cols]

# Clean column names
curated_df.columns = curated_df.columns.str.strip()

# Remove fully empty columns
curated_df = curated_df.dropna(axis=1, how='all')

# Convert empty strings to NA
curated_df = curated_df.replace('', pd.NA)

curated_df['active_hours'] = (
    curated_df['total_active_time'] / 3600
).round(2)

curated_df['url_has_utm_separator'] = (
    curated_df['snapshot.link_url']
    .str.contains(r'\?', na=False)
)

curated_df['malformed_url_flag'] = (
    curated_df['snapshot.link_url']
    .str.contains('utm_', na=False)
    &
    ~curated_df['snapshot.link_url']
    .str.contains(r'\?', na=False)
)

def fix_missing_question(url):

    if pd.isna(url):
        return url

    if 'utm_' in url and '?' not in url:
        return url.replace('utm_', '?utm_')

    return url

curated_df['fixed_url'] = curated_df['snapshot.link_url'].apply(fix_missing_question)

from urllib.parse import urlparse, parse_qs

def parse_utm(url):
    if pd.isna(url):
        return pd.Series({
            'domain': None,
            'url_path': None,
            'utm_source': None,
            'utm_medium': None,
            'utm_campaign': None,
            'utm_term': None,
            'utm_content': None
        })

    parsed_url = urlparse(str(url))
    query = parse_qs(parsed_url.query)

    return pd.Series({
        'domain': parsed_url.netloc,
        'url_path': parsed_url.path,
        'utm_source': query.get('utm_source', [None])[0],
        'utm_medium': query.get('utm_medium', [None])[0],
        'utm_campaign': query.get('utm_campaign', [None])[0],
        'utm_term': query.get('utm_term', [None])[0],
        'utm_content': query.get('utm_content', [None])[0]
    })

utm_df = curated_df['snapshot.link_url'].apply(parse_utm)

curated_df = pd.concat([curated_df, utm_df], axis=1)

def parse_campaign(campaign):
    if pd.isna(campaign):
        return pd.Series({
            'country': None,
            'retailer': None,
            'funding_type': None,
            'platform': None,
            'channel': None,
            'supplier_entity': None,
            'brand': None,
            'category_code': None,
            'campaign_period': None,
            'asset_code': None,
            'creative_format': None
        })

    parts = str(campaign).split('_')

    return pd.Series({
        'country': parts[0] if len(parts) > 0 else None,
        'retailer': parts[1] if len(parts) > 1 else None,
        'funding_type': parts[2] if len(parts) > 2 else None,
        'platform': parts[3] if len(parts) > 3 else None,
        'channel': parts[4] if len(parts) > 4 else None,
        'supplier_entity': parts[5] if len(parts) > 5 else None,
        'brand': parts[6] if len(parts) > 6 else None,
        'category_code': parts[7] if len(parts) > 7 else None,
        'campaign_period': parts[8] if len(parts) > 8 else None,
        'asset_code': parts[9] if len(parts) > 9 else None,
        'creative_format': parts[-1] if len(parts) > 0 else None
    })

campaign_df = curated_df['utm_campaign'].apply(parse_campaign)

curated_df = pd.concat([curated_df, campaign_df], axis=1)

def extract_first_card_value(cards, key):
    if isinstance(cards, list) and len(cards) > 0 and isinstance(cards[0], dict):
        return cards[0].get(key)
    return None

curated_df['card_title'] = curated_df['snapshot.cards'].apply(lambda x: extract_first_card_value(x, 'title'))
curated_df['card_body'] = curated_df['snapshot.cards'].apply(lambda x: extract_first_card_value(x, 'body'))
curated_df['card_cta_text'] = curated_df['snapshot.cards'].apply(lambda x: extract_first_card_value(x, 'cta_text'))
curated_df['card_link_url'] = curated_df['snapshot.cards'].apply(lambda x: extract_first_card_value(x, 'link_url'))

curated_df['card_image_url'] = curated_df['snapshot.cards'].apply(lambda x: extract_first_card_value(x, 'original_image_url'))
curated_df['card_video_hd_url'] = curated_df['snapshot.cards'].apply(lambda x: extract_first_card_value(x, 'video_hd_url'))
curated_df['card_video_sd_url'] = curated_df['snapshot.cards'].apply(lambda x: extract_first_card_value(x, 'video_sd_url'))

text_cols = [
    'funding_type',
    'supplier_entity',
    'brand',
    'creative_format',
    'utm_source',
    'utm_medium'
]

for col in text_cols:
    if col in curated_df.columns:
        curated_df[col] = curated_df[col].astype(str).str.strip().str.lower()

curated_df['funding_type_label'] = curated_df['funding_type'].replace({
    'coop': 'Coop',
    'house': 'House',
    'o&o': 'O&O',
    'oa': 'O&O'
})

curated_df['brand_label'] = curated_df['brand'].str.replace('-', ' ', regex=False).str.title()
curated_df['supplier_label'] = curated_df['supplier_entity'].str.replace('-', ' ', regex=False).str.title()

curated_df['ad_archive_id'] = curated_df['ad_archive_id'].astype(str)
curated_df['collation_id'] = curated_df['collation_id'].astype(str)

deduped_df = curated_df.drop_duplicates(subset=['ad_archive_id'])

final_cols = [
    'ad_archive_id',
    'collation_id',
    'is_active',
    'start_date_formatted',
    'end_date_formatted',
    'page_name',
    'snapshot.page_name',
    'snapshot.title',
    'snapshot.body.text',
    'snapshot.cta_text',
    'snapshot.display_format',
    'snapshot.link_url',
    'domain',
    'url_path',
    'utm_source',
    'utm_medium',
    'utm_campaign',
    'funding_type_label',
    'supplier_label',
    'brand_label',
    'campaign_period',
    'creative_format',
    'card_title',
    'card_body',
    'card_cta_text',
    'card_image_url',
    'card_video_hd_url',
    'publisher_platform'
]

final_df = deduped_df[[col for col in final_cols if col in deduped_df.columns]].copy()

import ast
import pandas as pd

def clean_platforms(x):

    # Handle None / NaN
    if x is None:
        return None

    # If already a list
    if isinstance(x, list):
        return ', '.join(x)

    # If string representation of list
    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)

            if isinstance(parsed, list):
                return ', '.join(parsed)

            return x

        except:
            return x

    return str(x)

final_df['publisher_platform_clean'] = final_df['publisher_platform'].apply(clean_platforms)

platforms = [
    'FACEBOOK',
    'INSTAGRAM',
    'AUDIENCE_NETWORK',
    'MESSENGER',
    'THREADS'
]

for platform in platforms:
    final_df[platform.lower()] = final_df['publisher_platform_clean'].str.contains(
        platform,
        case=False,
        na=False
    )

def classify_page(path):

    if pd.isna(path):
        return 'Unknown'

    path = str(path).lower()

    if path == '/':
        return 'Homepage'

    elif '/product/' in path or '/buy/' in path:
        return 'SKU Product'

    elif '/shop-online/' in path:
        return 'Brand/Category Page'

    elif '/search' in path:
        return 'Search Page'

    elif '/store-locator' in path:
        return 'Store Locator'

    elif '/plans' in path:
        return 'Plans/Pricing Page'

    elif '/canvas_doc/' in path:
        return 'Internal/App Page'

    elif 'vaccination' in path or 'event' in path:
        return 'Health Service / Event Page'

    elif 'sale' in path or 'promo' in path or 'mayhem' in path:
        return 'Promo Landing Page'

    return 'Other'

final_df['landing_page_type'] = (
    final_df['url_path']
    .apply(classify_page)
)

final_df['is_official_cw'] = (
    final_df['page_name']
    .astype(str)
    .str.lower()
    .str.contains('chemist warehouse')
)

final_df['mentions_cw_brand'] = (
    final_df['snapshot.title']
    .astype(str)
    .str.lower()
    .str.contains('chemist warehouse')
    |
    final_df['snapshot.body.text']
    .astype(str)
    .str.lower()
    .str.contains('chemist warehouse')
)

tga_keywords = [
    'cure',
    'fat loss',
    'weight loss',
    'prevent disease',
    'miracle',
    'rapid results'
]

pattern = '|'.join(tga_keywords)

final_df['tga_risk_flag'] = (
    final_df['snapshot.title']
    .astype(str)
    .str.lower()
    .str.contains(pattern)
    |
    final_df['snapshot.body.text']
    .astype(str)
    .str.lower()
    .str.contains(pattern)
)

supplier_sov = (
    final_df.groupby('supplier_label')
    .size()
    .reset_index(name='ad_count')
)

supplier_sov['share_of_voice_pct'] = (
    supplier_sov['ad_count']
    / supplier_sov['ad_count'].sum()
) * 100

final_df['snapshot_date'] = pd.to_datetime('today').date()

final_df['start_date_formatted_dt'] = pd.to_datetime(
    final_df['start_date_formatted'],
    format='%Y-%m-%d %H:%M:%S',
    errors='coerce'
)

pipeline_run_datetime = pd.Timestamp.now(tz='Australia/Sydney').tz_localize(None)

final_df['snapshot_run_datetime'] = pipeline_run_datetime

final_df['campaign_age_days'] = (
    final_df['snapshot_run_datetime'] - final_df['start_date_formatted_dt']
).dt.days

def run_dq_checks(final_df):

    checks = {
        'duplicate_ad_archive_id': final_df['ad_archive_id'].duplicated(keep=False).sum(),
        'missing_page_name': final_df['page_name'].isna().sum(),
        'invalid_start_date': final_df['start_date_formatted_dt'].isna().sum(),
        'future_start_date': (final_df['start_date_formatted_dt'] > pd.Timestamp.today()).sum(),
        'blank_creative_text': (
            final_df['snapshot.title'].isna()
            & final_df['snapshot.body.text'].isna()
        ).sum()
    }

    dq_summary = pd.DataFrame({
        'dq_check': checks.keys(),
        'failed_records': checks.values(),
        'total_records': len(final_df)
    })

    dq_summary['failure_rate_pct'] = (
        dq_summary['failed_records'] / dq_summary['total_records'] * 100
    ).round(2)

    dq_summary['pipeline_run_datetime'] = pd.Timestamp.now()

    return dq_summary

dq_summary = run_dq_checks(final_df)

display(dq_summary)

critical_failures = dq_summary[
    dq_summary['dq_check'].isin([
        'duplicate_ad_archive_id',
        'invalid_start_date',
        'future_start_date'
    ])
]['failed_records'].sum()

if critical_failures > 0:
    print("Pipeline failed due to critical data quality issues.")
else:
    final_df.to_csv('meta_ads_final_updated.csv', index=False)
    dq_summary.to_csv('meta_ads_dq_summary.csv', index=False)
    print("Pipeline passed. Final dataset exported.")

# Export files
final_df.to_csv('meta_ads_final_updated.csv', index=False)

dq_summary.to_csv(
    'meta_ads_dq_summary.csv',
    index=False
)

# Download files
from google.colab import files

files.download('meta_ads_final_updated.csv')
files.download('meta_ads_dq_summary.csv')
